# Episode 01: Puzzle basics and problem understanding

TODO

**Goals for this episode:**
- Name the concepts
- Define how to represent the puzzle for experiments

## Prologue

TODO Prologue as a separate document 
- 1. game description
- 2. project goals

experiment with solution patterns, compare, learn some python

this can be used as a tutorial

# 1. Name the concepts of the puzzle

I often find people stuck when it comes to start the design of an application:
- Where do I start ? 
- What are the classes ? 
- What should tjey do ?

I always find useful to state what we know about the problem clearly and in a consistent vocabulary. 

Most of time 
- **names** roughly map to **entities** or **attributes** of these entities: e.g. concepts, information shared by entities, width, height
- and **verbs** roughly map to **operations** on these entities: e.g. create, check whether some rule is held or broken

As for now I see the puzzle the way it is listed below. 

- the goal is to **fill** a **board**
- the **board** consists of **cells**
- the **board** organizes **cells** horizontally in **rows** 
- the **board** organizes **cells** vertically in **columns** (shorten as **cols**) 
- each **cell** has a **state** which is **undefined**, **solid/black** or **filler**
- **puzzle** **input** is given as a **list of clues** 
- a **clue** is given for each **row** and for each **column**   
- **clue** is either a **number** or a **list of numbers** 
- when the **clue** is only one **number** in the **row** or **column** the **number** tells the **size** of the **block of contiguous black cells**
- when the **clue** is a **list of numbers** there are multiple **blocks of contiguous black cells** in the row or column 
- the **puzzle** is **solved** when the **state** pf each **cell** is either a **black** or a **filler** and they are so that if I **count** the **blocks of contiguous blocks of cells** it **holds** the **clues**

# 2. Design the problem

How can we go from there ?

Now we have names and verbs here is a very simple design problem statement

**Potential entities:**
- board 
    - board has many cells
        - cell has a state with one of undefined, black and filler
    - board has many rows
        - row has a width (implicit)
    - board has many columns
        - has a height (implicit)
    - board has blocks of contiguous cells
- puzzle
    - puzzle has many clues
        - clue belong to a row or a column
            - clue is a number or a list of number 
            - number is an integer (implicit)
 
**Potential operations:**
- create the puzzle 
    - given the clues as input
- fill a board with a cell state
    - given a cell and a state
- check whether the board is solved
    - compare clues with board states
- get the solved board 
    - read the board

It is pretty clear that we have at least two entities puzzle and board. Other elements are presummably attributes of these entities.

As for operation, the first one relate to puzzle and 3 others to board.

## 3. Implement the Puzzle entity 

You can stop and think for yourself how you would implement this entity.

Remember we need numbers or list of numbers for each row and column.

**...**

As often in design there are many options depending on how we split work, the time we have, what we are confortable with.

Considerations made first choice:
- stick with a very simple implementation in order to have something workable as soon as possible
- readability of the puzzle description

The chosen implementation is:
- stick with a simple dictionnary and wait until a class is required to implement it
- the dictionnary a tow items rows and cols
- each item is a list of either number or list of numbers (readability)


Please note that the list containts differen types of elements. They will need to be handled carefully. Namely integers will have to be converted to a list to use the list elements in a consistent way. This will provide interesting Python challenges.

In [1]:
# given input for a 2x2 puzzle

# Please note that list are base 0 in Python 
# Thus clues['cols'][0] is the left most column
#     and clues['cols'][1] is the second columns from the left

# 1 denotes that the row has 1 contiguous black cells 
#     and a filler of 1 which position is unknown
# 2 denotes that all cells are black

clues2x2 = {
    'rows': [1, 2],
    'cols': [2, 1]
}

# If o marks blacks and x marks fillers, the solution is 
# ox
# xx 

In [2]:
# game instructions for a 5x5 game

# Please note that list are base 0 in Python 
# Thus clues['cols'][0] is the left most column
#     and clues['cols'][1] is the second columns from the left

# 4 denotes that the col has 4 contiguous black cells 
#     and a filler of 1 which position is unknown
# [2,2] denotes that col split blocks 
#     2 contiguous black cells, 
#     a filler which size is unknows 
#     and 2 contiguous black cels

clues5x5s = {
    'rows': [1, 3, [1,1], 3, 5],
    'cols': [1, 4, [2,2], 4, 1]
}

# If o marks blacks and x marks fillers, the solution is 
# xxoxx
# xooox
# xoxox
# xooox
# ooooo

## 4. Implement the Board entity 

You can stop and think for yourself how you would implement this entity.

Remember we need a board of w by h cells where w is width and h is height, an operation fill the board's cell with three states: undefined, black, filler.

In order to have somethig workable rapidly we will focus on representing the board ans leave check operation for abother episode.

**...**

As often in design there are many options depending on how we split work, the time we have, what we are confortable with.

Considerations made first choice:
- stick with a very simple implementation 
- leave solution validation for future work

The chosen implementation is:
- a class as a know already that some operations must be provided (fill, print)
- an Numpy arryarray of cells
- an enum of states to avoid "magic strings" and document the values
- a fill operation to change the state of a cell 
- a prettyprint operation to print the board and clues


## 4.1. Numpy array

Python list would do the job. 

For instance
- a list of rows of cells: [["A", "B"], ["C", "D"]]
- or a list of cells: [ "A", "B", "C", "D"]

The continuous list would suit as well because a position can be computed from rows and cols.

In [3]:
array1D = [ "A", "B", "C", "D"]
array2D = [ ["A", "B"], ["C", "D"]]
height = len(array2D)
width = len(array2D[0])

# compute position in 1D array from row and col
get_pos = lambda r,c: r*width + c

for row in range(height):
    for col in range(width): 
        pos = get_pos(row,col)
        print(f"r:{row}, c:{col} -> pos:{pos} - 1D:{array1D[pos]} - 2D:{array2D[row][col]}")

r:0, c:0 -> pos:0 - 1D:A - 2D:A
r:0, c:1 -> pos:1 - 1D:B - 2D:B
r:1, c:0 -> pos:2 - 1D:C - 2D:C
r:1, c:1 -> pos:3 - 1D:D - 2D:D


Best choice depends on the use cases. 

We do not have to care too much about this decision Numpy provides an efficient way of storing matrix and is widely used.

In addition numpy allows to change the shape, for instance to witch between two dimensions and one when needed.

In [4]:
# need to import numpy library
# it is provided in most Python environment. If not you install it with pip install numpy
import numpy as np

In [5]:
# create a 2x2 board of type int, initialized with -1
states = np.full((2, 2), -1, dtype=int)
states

array([[-1, -1],
       [-1, -1]])

In [6]:
# fill the solution to the game
# index is row, cell
states[0,0] = 1
states[0,1] = 0
states[1,0] = 1
states[1,1] = 1
states

array([[1, 0],
       [1, 1]])

In [7]:
# reshape to a contiguous list of size width* height
states.reshape(width*height)

array([1, 0, 1, 1])

Please not that there are many other ways to represent a board. You may want to use a network of cells linked to each other horizontally and vertically. It might be useful if moving from a cell to its adjacent cells is a frequent operation or you want to apply some graph theory capability.

However 1D or 2D lists are the most frequent.

## 4.2. Enum for state values

We will need some convention to store the state of the cells as undefined, black or filler

The convention here is:
- undefined : -1
- filler : 0
- black/solid : 1

Rationale:
- The rationale is that the sum of blacks should be easy to compare with the ckue value. So black should be 1. 
- It make sense that fillers are 0 so they do not alter the sums. 
- Undefined could be anything we can filter out easily.

Python as many other langages provide a way to list symbolic names or constants and group them by their meaning.

For instance we can create an Enum of all the BoardMark the use may use to fill the board. 

In [8]:
# need to import enum. It is built in in the Python engine
from enum import Enum

# constants for marks
class BoardMark(Enum):
    INIT = -1
    FILLER = 0
    BLACK = 1

In [9]:
# BoardMark.BLACK will be passed as a parameter to the fill function
print(BoardMark.BLACK)

BoardMark.BLACK


In [10]:
# as we have an array of -1,0,1 the enum will need to be converted into a value
print(BoardMark.BLACK.value)

1


In [11]:
# fill the cell with a mark
def mark(row, col, state):
    # index is row, cell
    states[row, col] = state.value

mark(0, 0, BoardMark.BLACK)
mark(0, 1, BoardMark.FILLER)
mark(1, 0, BoardMark.BLACK)
mark(1, 1, BoardMark.BLACK)
states

array([[1, 0],
       [1, 1]])

## 4.3. Board representation

We will also need to represent the board visually in order to check what happen.

To start with we will use a simple representation of the board. Each value can be converted into a character:
- undefined : .
- filler : x
- black/solid : o

I make the assumption that the board can be represented later as a plot with matplotlib. Lease this for another episode.

In [12]:
# dictionnaries are used in Python to describe swich cases depending on the value
marks_switches = {BoardMark.INIT.value:   '.', 
                  BoardMark.FILLER.value: 'x', 
                  BoardMark.BLACK.value:  'o'}
print(marks_switches[BoardMark.INIT.value])
print(marks_switches[BoardMark.FILLER.value])
print(marks_switches[BoardMark.BLACK.value])

.
x
o


In [13]:
# The switcher can be applyed to the full array
# numpy provides ways to apply a function to all the cells
# must use vectorize, for whatever reason lambda does not work here
def switch_mark(v):
    return marks_switches[v]
apply_all_switch_mark = np.vectorize(switch_mark)
states_repr = apply_all_switch_mark(states)
states_repr

array([['o', 'x'],
       ['o', 'o']], dtype='<U1')

# 5. Class implementation

In [14]:
# reset all variables from tests
%reset -f

In [15]:
# need to import numpy library
# it is provided in most Python environment. If not you install it with pip install numpy
import numpy as np
# need to import enum. It is built in in the Python engine
from enum import Enum

class BoardMark(Enum):
    '''
    Constants for board marks
    '''
    INIT = -1
    FILLER = 0
    BLACK = 1

class Board:
    '''
    Manage the board.
    '''
    
    def __init__(self, some_clues):
        '''
        board constructor
        '''
        # given parameters
        self.clues = some_clues
        
        # compute board dimensions
        self.width = len(self.clues['cols']) 
        self.height = len(self.clues['rows'])
        
        # create board of type int, initialized with -1
        default_value = BoardMark.INIT.value
        self.states = np.full((self.height, self.width), default_value, dtype=int)
        
    def mark(self, row, col, mark):
        '''
        fill the cell with a mark
        '''
        self.states[row, col] = mark.value

    def prettyprint(self):
        '''
        pretty print of the board 
        '''
        print("cols:", end=" ")
        print(*self.clues['cols']) # * unpacks and remove []s
        print("rows:")
        [print(r) for r in self.clues['rows']]
          
        # dictionnaries are used in Python to describe swich cases depending on the value
        marks_switches = {BoardMark.INIT.value:   '.', 
                          BoardMark.FILLER.value: 'x', 
                          BoardMark.BLACK.value:  'o'}
        
        # The switch can be applyed to the full array
        # numpy provides ways to apply a function to all the cells
        # must use vectorize, for whatever reason lambda does not work here
        def switch_mark(v):
            return marks_switches[v]
        
        apply_all_switch_mark = np.vectorize(switch_mark)
        states_repr = apply_all_switch_mark(self.states)
        states_repr        
        
        print(states_repr)


## 5.1. Check 2x2 board

In [16]:
clues2x2 = {
    'rows': [1, 2],
    'cols': [2, 1]
}
board2x2 = Board(clues2x2)
board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['.' '.']
 ['.' '.']]


In [17]:
# give the solution to the game
# index is row, cell
board2x2.mark(0, 0, BoardMark.BLACK) 
board2x2.mark(0, 1, BoardMark.FILLER) 
board2x2.mark(1, 0, BoardMark.BLACK) 
board2x2.mark(1, 1, BoardMark.BLACK) 

board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['o' 'x']
 ['o' 'o']]


In [18]:
# internak of the board class are accessible
print(board2x2.clues)
print(f"width:{board2x2.width}, height:{board2x2.height}")
print(board2x2.states)

{'rows': [1, 2], 'cols': [2, 1]}
width:2, height:2
[[1 0]
 [1 1]]


## 5.2. Check 5x5 split board

In [19]:
clues5x5s = {
    'rows': [1, 3, [1,1], 3, 5],
    'cols': [1, 4, [2,2], 4, 1]
}
board5x5s = Board(clues5x5s)
board5x5s.prettyprint()

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']]


## 5.3. Check non square board

In case width and height are mixed up

In [20]:
clues4x2 = {
    'rows': [1, 2, 1, 2],
    'cols': [2, 1]
}
board4x2 = Board(clues4x2)
board4x2.prettyprint()

cols: 2 1
rows:
1
2
1
2
[['.' '.']
 ['.' '.']
 ['.' '.']
 ['.' '.']]


## 6. Wrap up

We have learned
- how to analyze the problem
- basics of numpy
- enum
- switch with dicst

The class and clues are saved in episode01.py.

We now have basic component to work a solution.



## 6.1. Quick test of saved classes

In [21]:
# reset all variables from tests
%reset -f

In [22]:
from episode01 import clues2x2, BoardMark, Board

In [23]:
board2x2 = Board(clues2x2)
board2x2.mark(0, 0, BoardMark.BLACK) 
board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['o' '.']
 ['.' '.']]


# TODO - move the prologue in another episode