# Episode 02: First Hands On

TODO

**Goals for this episode:**
- Try to solve the puzzle leveraging classes of Episode 01
- List potential strategies or heuristics
- List what we need for POCs

Now we have a board, we can test some ways to solve the puzzle.

# 1. Mimic manual process

Having an idea from scratch is difficult.

As a starter let's solve the board manually and check what we can learn

## 1.1. Manually solve 2x2

In [5]:
from episode01 import clues2x2, BoardMark, Board

In [6]:
board2x2 = Board(clues2x2)
board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['.' '.']
 ['.' '.']]


In [7]:
print(clues2x2)

{'rows': [1, 2], 'cols': [2, 1]}


In [8]:
# because clues2x2['rows'][1] is 2 and width is 2, all cells of row 1 are black
board2x2.states[1,:] = BoardMark.BLACK.value
# because clues2x2['cols'][0] is 2 and height is 2, all cells of col 0 are black
board2x2.states[:,0] = BoardMark.BLACK.value
board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['o' '.']
 ['o' 'o']]


In [9]:
# has there is already 1 black on the row and col, top right cell is a filler
board2x2.states[0,1] = BoardMark.FILLER.value
board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['o' 'x']
 ['o' 'o']]


Voila!

Thus board is overly simple. Lat's try the 5 by 5 with splits.

## 1.2. Manually solve 5x5 split

In [10]:
from episode01 import clues5x5s, BoardMark, Board

In [11]:
board5x5s = Board(clues5x5s)
board5x5s.prettyprint()

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']]


In [12]:
print(clues5x5s)

{'rows': [1, 3, [1, 1], 3, 5], 'cols': [1, 4, [2, 2], 4, 1]}


In [13]:
# because clues5x5s['rows'][4] is 5 and width is 5, all cells of row 4 are black
board5x5s.states[4,:] = BoardMark.BLACK.value
board5x5s.prettyprint()

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.']
 ['o' 'o' 'o' 'o' 'o']]


In [14]:
# because clues5x5s['cols'][2] is [2,2] and height is 5,
# there must be a filler in row 2 and other cells are black
board5x5s.states[:,2] = BoardMark.BLACK.value
board5x5s.states[2,2] = BoardMark.FILLER.value
board5x5s.prettyprint()

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['.' '.' 'o' '.' '.']
 ['.' '.' 'o' '.' '.']
 ['.' '.' 'x' '.' '.']
 ['.' '.' 'o' '.' '.']
 ['o' 'o' 'o' 'o' 'o']]


In [15]:
# because clues5x5s['cols'][1] is 4 and there is a black in row 4
# the contiguous block of black cells must span from row 1 to row 4
# same for clues5x5s['cols'][3]
board5x5s.states[:,1] = BoardMark.BLACK.value
board5x5s.states[:,3] = BoardMark.BLACK.value
board5x5s.states[0,1] = BoardMark.FILLER.value
board5x5s.states[0,3] = BoardMark.FILLER.value
board5x5s.prettyprint()

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['.' 'x' 'o' 'x' '.']
 ['.' 'o' 'o' 'o' '.']
 ['.' 'o' 'x' 'o' '.']
 ['.' 'o' 'o' 'o' '.']
 ['o' 'o' 'o' 'o' 'o']]


In [16]:
# because clues5x5s['rows'][1] is 3 and 3 black are placed on the row
# first and lasr cells mustrt be fillers
# same for clues5x5s['rows'][4]
board5x5s.states[1,0] = BoardMark.FILLER.value
board5x5s.states[1,4] = BoardMark.FILLER.value
board5x5s.states[3,0] = BoardMark.FILLER.value
board5x5s.states[3,4] = BoardMark.FILLER.value
board5x5s.prettyprint()

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['.' 'x' 'o' 'x' '.']
 ['x' 'o' 'o' 'o' 'x']
 ['.' 'o' 'x' 'o' '.']
 ['x' 'o' 'o' 'o' 'x']
 ['o' 'o' 'o' 'o' 'o']]


In [17]:
# as every black has been placed remaining cells are fillers
board5x5s.states[0,0] = BoardMark.FILLER.value
board5x5s.states[0,4] = BoardMark.FILLER.value
board5x5s.states[2,0] = BoardMark.FILLER.value
board5x5s.states[2,4] = BoardMark.FILLER.value
board5x5s.prettyprint()

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['x' 'x' 'o' 'x' 'x']
 ['x' 'o' 'o' 'o' 'x']
 ['x' 'o' 'x' 'o' 'x']
 ['x' 'o' 'o' 'o' 'x']
 ['o' 'o' 'o' 'o' 'o']]


Voila

## 1.3 . Where the difficulty comes from ?

- large blocls are easier to place, especially the ones that span over all the width or height
- borders are useful as once a black is placed at a borders all the block of contiguous cells can be placed
- small blocks required a lot of guessing
- split are tricky to manage. First they cause blocks to be smaller. Second, they require to guess even more, you have to make a guess for each block
- an exception is when the filler between blocks is exactly one and all other cells are black. As exemple think of [2,2] over 5


## 1.4. Wrap up

You may implement a series of rules, to mimic this process. But think of the number of rules and the number of tests you may have to implement to feature out which rule applies when.

Well, it is tedious, tricky to implement. And not funny!

I will not implement it. However trying to solve the problem manually help understanding the internals of the problem and what works in a robot.

When a human solves the board, doing tons of computations for each cell is boring. Human tends to rely on more visual clues like proximity, overall shape and symetry. Most of this information is not provided by the clues but our human brain knows that the puzzle boils down to an image and there must be some logic in this image. Nonogram are not supposed to be random scattered plots. 

This reasoning is far beyond what the numeric algorithm can do. 

On the other hand, nonograms are small and computations for a 15x15 matrix are cheap and fast. The problem space (the number of possible options) is reasonably small. From a more general perspective,  putting some rules in the robot may be more efficient than bare computation if rules are carefully chosen bedcause it reduces the problem space.

# 2. Try-and-error process

Having an idea from scratch is difficult.

The contract with the platyer for Nonograms is that they always have 1 solution. Let's say we know that there is a solution. We can try different values for each cell until the board is solved.

Even if this process is probably not what we want, it will help undestand what we need to solve the puzzle. 

In addition, it make sense in AI. Some algorithms, especially in Reinforcement Learning, work by learning from try-and-error process. They are given the goal to keep errors to a minimulm.

Lets's say that the solution is known.

We can implement a trial and error process.


In [18]:
# save solutions to numpy arrays
solution2x2 = board2x2.states.copy()
solution5x5s = board5x5s.states.copy()

In [19]:
solution5x5s

array([[0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

What could be the try-and-error process ?

For each cell, I know that it could be black or filler. 

We need some game engine to decide whether the action is valid or not according to be solution it knows already. 

## 2.1. Validation and puzzle utilities

In [20]:
class GameEngine:
    def __init__(self, some_clues, a_solution):
        self.clues = some_clues
        self.solution = a_solution
        
    def is_action_valid(self, row, col, mark):
        return self.solution[row, col] == mark.value

In [21]:
solution2x2

array([[1, 0],
       [1, 1]])

In [22]:
engine2x2 = GameEngine(clues2x2, solution2x2)
engine2x2.is_action_valid(1,1, BoardMark.BLACK)

True

In [23]:
engine2x2.is_action_valid(0,1, BoardMark.BLACK)

False

Now, let's loop over the problem space

## 2.2. Experiments

In [24]:
from episode01 import clues2x2, BoardMark, Board

In [25]:
board2x2 = Board(clues2x2)
error_count = 0
for row in range(board2x2.height):
    for col in range(board2x2.width):
        if engine2x2.is_action_valid(row, col, BoardMark.BLACK):
            board2x2.mark(row, col, BoardMark.BLACK)
        else: 
            error_count += 1
            board2x2.mark(row, col, BoardMark.FILLER)

board2x2.prettyprint()
print(f"error_count:{error_count}")

cols: 2 1
rows:
1
2
[['o' 'x']
 ['o' 'o']]
error_count:1


Voila!

I agree that this algorithm is pretty dump. The percentage of errors goes up very rapidly and exceed what the game will accept (usually 3 errors). On the 5x5 board it took 11 errors to solve 25 cells.

In [26]:
engine5x5s = GameEngine(clues5x5s, solution5x5s)
board5x5s = Board(clues5x5s)
error_count = 0
for row in range(board5x5s.height):
    for col in range(board5x5s.width):
        if engine5x5s.is_action_valid(row, col, BoardMark.BLACK):
            board5x5s.mark(row, col, BoardMark.BLACK)
        else: 
            error_count += 1
            board5x5s.mark(row, col, BoardMark.FILLER)

board5x5s.prettyprint()
print(f"error_count:{error_count}")

cols: 1 4 [2, 2] 4 1
rows:
1
3
[1, 1]
3
5
[['x' 'x' 'o' 'x' 'x']
 ['x' 'o' 'o' 'o' 'x']
 ['x' 'o' 'x' 'o' 'x']
 ['x' 'o' 'o' 'o' 'x']
 ['o' 'o' 'o' 'o' 'o']]
error_count:11


# 2.3  Wrap up

What works:
- it is really simple to design and implement
- no computation, no headache with split blocks

Limitation:
- requires that the solution is known beforehand
- roughly 50% error rate. It depends on the proportion of blacks and fillers,  and whether blacks or fillers are checked for validity

# 3. Brute Force

The idea behind brute force is to generate all possible options and then check which one is vaid.

Unlike try-and-error the validation will take place on the whole board. We do not need to know the solution beforehand. The engine can compute the clues from the board and check whether the board holds or breaks the clues.

## 3.1 Validation of a proposed board state

For various experiments we will need the same operations
- compute the shape of the board from the clues
- compute the number of cells
- compute tne number of blacks cells to be placed
- verify that the board is solved

For this episode we focus on simple board without split blocks and we assume that here that the solutions is known and given to the game engine.

In [27]:
clues2x2

{'rows': [1, 2], 'cols': [2, 1]}

In [28]:
black_count = sum(clues2x2['rows'])
black_count

3

In [29]:
cells_count = len(clues2x2['rows']) * len(clues2x2['cols'])
cells_count

4

In [30]:
# create the game engine from the hanfscrafted solution
engine2x2 = GameEngine(clues2x2, solution2x2)

In [31]:
engine2x2.solution.tolist()

[[1, 0], [1, 1]]

In [32]:
# reshape flat the list into a 1D array
flat_solution_2x2 = engine2x2.solution.reshape(cells_count).tolist()
flat_solution_2x2

[1, 0, 1, 1]

In [33]:
flat_solution_2x2 == [1, 0, 1, 1]

True

In [34]:
flat_solution_2x2 == [0, 1, 1, 1]

False

In [35]:
class GameEngine:
    def __init__(self, some_clues, a_solution):
        self.clues = some_clues
        self.solution = a_solution
        
        self.width = len(some_clues['cols'])
        self.height = len(some_clues['rows'])
        self.black_count = sum(some_clues['rows'])
        self.cells_count = self.width * self.height
        
    def is_action_valid(self, row, col, mark):
        return self.solution[row, col] == mark.value        
    
    def is_board_valid(self, states_list):
        flat_solution = self.solution.reshape(self.cells_count).tolist()
        return  flat_solution == states_list
    

In [36]:
engine2x2 = GameEngine(clues2x2, solution2x2)
assert engine2x2.width == 2
assert engine2x2.height == 2
assert engine2x2.cells_count == 4
assert engine2x2.black_count == 3
assert engine2x2.is_board_valid([1, 0, 1, 1])
assert not engine2x2.is_board_valid([1, 1, 0, 1])

## 3.1. Experiment on 2x2

The first step is to list all possible options for the oard.

The board is a list of 0 and 1. From the clues we know the number of black cells. It is the sum of all clues for either rows or cols.

All possible boards are permutations of this black cells over the cells of the board. Given a set of [1,0] items, permutations are [1,0] and [0,1]

In [37]:
clues2x2

{'rows': [1, 2], 'cols': [2, 1]}

In [38]:
engine2x2 = GameEngine(clues2x2, solution2x2)
engine2x2.solution

array([[1, 0],
       [1, 1]])

In [39]:
from itertools import repeat, chain, tee
# 3 blacks
black_iterator = repeat(BoardMark.BLACK.value, engine2x2.black_count) 
# 1 filler
filler_iterator = repeat(BoardMark.FILLER.value, engine2x2.cells_count - engine2x2.black_count) 
# chain concatenate both iterators
# tee -is used for debugging, it duplicates the iterator which can be consummed only once
initial_states_iterator, debug_iterator = tee(chain(black_iterator, filler_iterator))
# show the value for debugging
list(debug_iterator)

[1, 1, 1, 0]

In [40]:
from itertools import permutations
# generate permutations 
permutations_iterator, debug_iterator = tee(permutations(initial_states_iterator))
list(debug_iterator)
# there are 16 because permutation switch elements of the list and not values
# it does not take care that 1 occurs many times

[(1, 1, 1, 0),
 (1, 1, 0, 1),
 (1, 1, 1, 0),
 (1, 1, 0, 1),
 (1, 0, 1, 1),
 (1, 0, 1, 1),
 (1, 1, 1, 0),
 (1, 1, 0, 1),
 (1, 1, 1, 0),
 (1, 1, 0, 1),
 (1, 0, 1, 1),
 (1, 0, 1, 1),
 (1, 1, 1, 0),
 (1, 1, 0, 1),
 (1, 1, 1, 0),
 (1, 1, 0, 1),
 (1, 0, 1, 1),
 (1, 0, 1, 1),
 (0, 1, 1, 1),
 (0, 1, 1, 1),
 (0, 1, 1, 1),
 (0, 1, 1, 1),
 (0, 1, 1, 1),
 (0, 1, 1, 1)]

In [41]:
import numpy as np

board2x2 = Board(clues2x2)
# set avoids duplicates generated by permutations
for o in set(permutations_iterator):
    print(f"option:{o}")
    # select valid options
    if engine2x2.is_board_valid(list(o)): # option is a tuple () not a lust
        print(f"valid:{o}")
        board2x2.states.flat[:] = o

option:(1, 1, 0, 1)
option:(1, 1, 1, 0)
option:(0, 1, 1, 1)
option:(1, 0, 1, 1)
valid:(1, 0, 1, 1)


In [42]:
board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['o' 'x']
 ['o' 'o']]


## 3.2. Experiment on 2x2 - Alternative implementation

Another way of analysing this problem is to get all possible indexs of black cells instead of all possible boards.

Let's say there is a jar with numbers from 0 to 3. These are possible positions of a cell in the board. I want to draw 3 numbers from the jar. This is named combination.

In [43]:
clues2x2

{'rows': [1, 2], 'cols': [2, 1]}

In [44]:
engine2x2 = GameEngine(clues2x2, solution2x2)
engine2x2.solution

array([[1, 0],
       [1, 1]])

In [45]:
from itertools import combinations, tee
# want to get 3 positions in a range 0 - 4 where 4 is the number of cells
# we want each position to be unique thus no replacement
temp_iterator = combinations(range(engine2x2.cells_count), engine2x2.black_count)
combinations_iterator, debug_iterator = tee(temp_iterator)
list(debug_iterator)

[(0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3)]

In [46]:
import numpy as np

board2x2 = Board(clues2x2)
for option in combinations_iterator:
    print(f"option:{option}")
    # compute the board state
    # put black at each position in combinations_iterator and fillers elsewhere
    states = np.full(engine2x2.cells_count, BoardMark.FILLER.value, dtype=int)
    # put black at each position in combinations_iterator and fillers elsewhere
    for pos in option:
        states.flat[pos] = BoardMark.BLACK.value
    
    # select valid options
    if engine2x2.is_board_valid(states.tolist()): 
        print(f"valid:{states}")
        # batch update the board flattent to 1D
        board2x2.states.flat[:] = states

option:(0, 1, 2)
option:(0, 1, 3)
option:(0, 2, 3)
valid:[1 0 1 1]
option:(1, 2, 3)


In [47]:
board2x2.prettyprint()

cols: 2 1
rows:
1
2
[['o' 'x']
 ['o' 'o']]


## 3.3. Wrap up

What works:
- it is simple to design and implement
- no computation, no headache with split blocks

Limitation:
- number of options  increase rapidly with the size of the board. 

In addition all these options will have to be checked for validity. We used known solutions here  because they are available but in a real use case we would evaluate whether the option match the clues for each option.

The number of options increases lower with implementation 2 because the problem space is smaller. It is the number of blacks instead of the number of cells (blacks are usually around 50% of cells). However it increases rapidly.

In [48]:
from itertools import combinations

In [49]:
%time
from itertools import combinations
black_count = 4
cells_count = 9
combinations_iterator = combinations(range(cells_count), black_count)
len(list(combinations_iterator))

CPU times: user 4 µs, sys: 6 µs, total: 10 µs
Wall time: 12.9 µs


126

In [50]:
%time
black_count = 7
cells_count = 16
combinations_iterator = combinations(range(cells_count), black_count)
len(list(combinations_iterator))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs


11440

In [51]:
%time
black_count = 14
cells_count = 25
combinations_iterator = combinations(range(cells_count), black_count)
len(list(combinations_iterator))

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 4.77 µs


4457400

# 4. Stategies and heuristics to POC

## Programming with constraints

TODO

## Dynamic programming

TODO

## Probabilistic approach

TODO

## Mathematic approach

TODO

## Genetic algorithm

"genetic algorithm (GA) is a metaheuristic inspired by the process of natural selection that belongs to the larger class of evolutionary algorithms (EA). Genetic algorithms are commonly used to generate high-quality solutions to optimization and search problems by relying on biologically inspired operators such as mutation, crossover and selection" - Wikipedia

TODO how could it work here, explain a little bit the selection process

## Machine Learning

TODO

# 5. Wrap up

We have learned
- how to solve the puzlle manually, by try-and-error and by brute force
- some POC ideas

The class and solutions are saved in episode02.py.


This quick exploration of ways of solving this problem show that we need some additional components :
- a better board representation
- a game engine which provides the game validation for try-and-error validation and solved board - for all kind of puzzles (we have tested 2x2 only)
- some operation thate were identified in episode 01: is the board completed, is the board valid
- a puzzle class with some operations to transform the clues and compute black count and cels count
- try-and-error and learning process will require something in between not done and done in order to improve on residual error or rewards:  number of cells completed/undefined, number of errors, number of valid cells


## 5.1. Quick test of saved classes

In [52]:
# reset all variables from tests
%reset -f

In [53]:
from episode01 import clues2x2
from episode02 import solution2x2, GameEngine

In [54]:
clues2x2

{'rows': [1, 2], 'cols': [2, 1]}

In [55]:
solution2x2

array([[1, 0],
       [1, 1]])

In [56]:
engine2x2 = GameEngine(clues2x2, solution2x2)
assert engine2x2.width == 2
assert engine2x2.height == 2
assert engine2x2.cells_count == 4
assert engine2x2.black_count == 3
assert engine2x2.is_board_valid([1, 0, 1, 1])
assert not engine2x2.is_board_valid([1, 1, 0, 1])

# TODO intro